### ISSUE TITLE
Login/Register error

### ISSUE THREAD

**Issue by Milamo** [imranhsayed/gatsby-woocommerce-themes#34]
Hi

I get this error when trying to login or register.

Unhandled Rejection (TypeError): Cannot read property 'message' of undefined onError packages/gatsby-woocommerce-theme/src/components/login/index.js:47
  44 | onError: (error) => {
  45 |   if (error) {
  46 |     if (!isEmpty(error)) {
  47 |       setErrorMessage(error.graphQLErrors[0].message);
  48 |     }
  49 |   }
  50 | },

**Comment by Milamo** [comment]
> 
> 
> Hi
> 
> I get this error when trying to login or register.
> 
> Unhandled Rejection (TypeError): Cannot read property 'message' of undefined onError packages/gatsby-woocommerce-theme/src/components/login/index.js:47
> 44 | onError: (error) => {
> 45 | if (error) {
> 46 | if (!isEmpty(error)) {
> 47 | setErrorMessage(error.graphQLErrors[0].message);
> 48 | }
> 49 | }
> 50 | },

Hi no worries I have fixed it, thank you...

**Comment by AUFrasier** [comment]
@Milamo  what did you do to fix this?  I'm running into the same issue.
