### ISSUE TITLE
TypeError: Cannot read property 'title' of null

### ISSUE THREAD

**Issue by usmanhabeeb2017** [imranhsayed/gatsby-woocommerce-themes#36]
Hi, 

i am getting following error 

FrontPage
C:/Users/ginje/Downloads/Compressed/gatsby-woocommerce-themes-main/gatsby-woocommerce-themes-main/packages/gatsby-woocommerce-theme/src/templates/front-page/index.js:9
   6 | import SEO from "../../components/seo";
   7 | import { getOgImage } from "../../utils/functions";
   8 | 
>  9 | const FrontPage = ( props ) => {
  10 | 
  11 | 	const {
  12 | 		      pageContext: {

118993 | var FrontPage = function FrontPage(props) {
  118994 |   var _props$pageContext = props.pageContext,
  118995 |       _props$pageContext$pa = _props$pageContext.page,
> 118996 |       title = _props$pageContext$pa.title,
         |                                     ^  118997 |       seo = _props$pageContext$pa.seo,
  118998 |       uri = _props$pageContext$pa.uri,
  118999 |       categories = _props$pageContext.categories,

how can i resolve this error

Thanks in advance.

**Comment by CiubancanCristian** [comment]
how did you fix that, i'm running into the same issue here, and i would love to know how you fixed it, thanks in advance

**Comment by usmanhabeeb2017** [comment]
Sorry for late reply. 
First of all please create home page have slug home. 
Create header and footer menu and a assign them to the appropriate Display location "HCMS Header Menu"

hope so this will resolve your issue

Thanks
