### ISSUE TITLE
Double image on single product page

### ISSUE THREAD

**Issue by usmanhabeeb2017** [imranhsayed/gatsby-woocommerce-themes#48]
i have checked the product carousel is calling more then one time 

const ProductCarousel = ( { galleryImages } ) => {
	console.log(render 😡');
	let slider1 = null;
	let slider2 = null;

	const [nav1, setNav1] = useState( null );
	const [nav2, setNav2] = useState( null );

	useEffect( () => {
		setNav1( slider1 )
		setNav2( slider2 )
	}, [slider1, slider2] );

	if ( isEmpty( galleryImages.nodes ) ) {
		return null;
	}

![image](https://user-images.githubusercontent.com/34313804/102399553-9773e800-4002-11eb-9be9-2dafe945d0fa.png)

**Comment by imranhsayed** [comment]
removed
